default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: react-rails-dev

test:
  <<: *default
  database: react-rails-test

production:
  <<: *default
  database: react-rails-production
