# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f00e4c9046e2f6c44ca94c3b7f33b5fbf7beaed258b407b38462682c5aa21cfbb8d8a9f1e7ab776b8e14d063e32cb12f5790b54f100a574a6c78a010674012a8

test:
  secret_key_base: b6955e4b7771acd23535f4516752106d9b211d5f6258cec7baa776246f3a6c7a00166a62765ea44c29ef593990b3c096f85b3d8ab3fce23565bcbf232a6b62e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
